version: '3.0'

services:
  database:
    image: daas-db
    build:
      context: scripts/containers/database
    ports:
      - "54320:5432"
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data

  server:
    image: daas
    command: npm start
    ports:
      - "4000:4000"
    links:
      - database
    environment:
      DATABASE_URL: postgres://daas:daas@database:5432/daas
      AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXXX
      AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXX
      AWS_REGION: sa-east-1
      AWS_AMI_ID: ami-xxxxxxxxxxxxxxxxx
      DOCKER_REPO: my-aws-account-id.dkr.ecr.eu-west-1.amazonaws.com/daas
      LOG_TRANSMISSION_ADDRESS: 172.0.0.1
      LOG_TRANSMISSION_PORT_CORE: 6002
      PORT: 4000
    restart: always

  worker:
    image: daas
    command: npm run worker
    links:
      - database
    environment:
      DATABASE_URL: postgres://daas:daas@database:5432/daas
      AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXXX
      AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXX
      AWS_REGION: sa-east-1
      AWS_AMI_ID: ami-xxxxxxxxxxxxxxxxx
      DOCKER_REPO: my-aws-account-id.dkr.ecr.eu-west-1.amazonaws.com/daas
      LOG_TRANSMISSION_ADDRESS: 172.0.0.1
      LOG_TRANSMISSION_PORT_CORE: 6002
    restart: always