version: '3.0'

services:
  database:
    image: daas-db
    build:
      context: scripts/containers/database
    ports:
      - "54320:5432"
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data

  server:
    image: daas
    command: npm start
    ports:
      - "4000:4000"
    env_file: .env

  worker:
    image: daas
    command: npm run worker
    env_file: .env