platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
- name: git-repo
- name: ami

outputs:
- name: user-data

params:
  - OUTPUT_DIR: user-data
  - DATABASE_URL: ((daas_env.DATABASE_URL))
  - AWS_ACCESS_KEY_ID: ((aws_role.access_key_id))
  - AWS_SECRET_ACCESS_KEY: ((aws_role.secret_access_key))

run:
  path: git-repo/scripts/deploy/generate-user-data.sh